accountapp/urls.py
from django.urls import path

from accountapp.views import about_us, album, main_

app_name = "accountapp"

urlpatterns = [
    path('about_us/', about_us, name='about_us'),
    path('albums/', album, name='album'),
    path('main/', main_, name='main'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'articleapp'

urlpatterns = [
    path('list/', TemplateView.as_view(template_name='articleapp/list.html'), name='list')
]

where/urls.py
from django.contrib import admin
from django.urls import path, include

from accountapp.views import main_

urlpatterns = [
    path('', main_, name='home'),

    path('admin/', admin.site.urls),
    path('account/', include('accountapp.urls')),
    path('articles/', include('articleapp.urls')),
]

accountapp/models.py
from django.db import models

# Create your models here.


class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

articleapp/models.py
from django.db import models

# Create your models here.

accountapp/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse


def about_us(request):
    return render(request, 'accountapp/about_us.html')


def album(request):
    return render(request, 'accountapp/album.html')


def main_(request):
    return render(request, 'accountapp/main.html')

articleapp/views.py
from django.shortcuts import render

# Create your views here.

accountapp/templates/accountapp/about_us.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}


    <div>

        <div>
            <div class="IHAGI_logo" style="text-align: right; margin: 6rem 2.5rem 5rem;">
                <h2><I>아름다움 다음 너머</I></h2>
                <hr style="margin: 1.5rem 0;">
            </div>
        </div>
        <div class="container-fluid" style="margin-bottom: 9rem">
            <div class="row" style="margin: 2rem">
                <div class="col-sm-5" style="margin-bottom: 2.5rem">
                    <div style="text-align: center; ">
                        <img src="https://picsum.photos/300/300?grayscale"
                                style="width: 85%; box-shadow: 0 0 0.5rem dimgrey;" alt="">
                    </div>
                </div>
                <div class="col-sm-7" style="text-align: center; padding: 0 1rem;">
                    <h4 style="font-family: 'Noto Serif KR', serif;
                     font-size: calc(.6rem + 1vw) !important;margin-top: 5vw">
                        - 어디에서 왔고 어디로 가는가 -
                    </h4>
                    <p style="margin: 2vw 0 0.5vw;
                    font-size: calc(.1rem + 1vw) !important"><I> " where come where go ? " </I></p>
                </div>
            </div>
        </div>

        <div class="container-fluid" style="margin: 9rem 0;" >
            <div class="row" style="margin: 2rem">
                <div class="col-sm-5" style="margin-bottom: 2.5rem">
                    <div style="text-align: center; ">
                        <img src="https://picsum.photos/300/300?grayscale"
                                style="width: 85%; box-shadow: 0 0 0.5rem dimgrey;" alt="">
                    </div>
                </div>
                <div class="col-sm-7" style="text-align: center; padding: 0 1rem;">
                    <h4 style="font-family: 'Noto Serif KR', serif;
                     font-size: calc(.6rem + 1vw) !important;margin-top: 5vw">
                        - 비츠로 -
                    </h4>
                    <p style="margin: 2vw 0 0.5vw;
                    font-size: calc(.1rem + 1vw) !important"><I> " 우리가 늘 함께라고 생각해 " </I></p>
                    <h3 style="text-align: right; margin: 16rem 11rem 0 0"><span><i class="bi bi-instagram"></i></span></h3>
                </div>
            </div>
        </div>

        <div class="container-fluid" style="margin: 9rem 0;" >
            <div class="row" style="margin: 2rem">
                <div class="col-sm-5" style="margin-bottom: 2.5rem">
                    <div style="text-align: center; ">
                        <img src="https://picsum.photos/300/300?grayscale"
                                style="width: 85%; box-shadow: 0 0 0.5rem dimgrey;" alt="">
                    </div>
                </div>
                <div class="col-sm-7" style="text-align: center; padding: 0 1rem;">
                    <h4 style="font-family: 'Noto Serif KR', serif;
                     font-size: calc(.6rem + 1vw) !important;margin-top: 5vw">
                        - 전우뇌 -
                    </h4>
                    <p style="margin: 2vw 0 0.5vw;
                    font-size: calc(.1rem + 1vw) !important"><I> " 우렁찬 소리와 함께 " </I></p>
                </div>
            </div>
        </div>


    </div>



{% endblock %}

accountapp/templates/accountapp/album.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


    <div>

        <div>
            <div class="IHAGI_logo" style="text-align: right; margin: 6rem 2.5rem 6rem;">
                <h2><I>OUR ALBUMS</I></h2>
                <hr style="margin: 1rem 0;">
            </div>
        </div>
        <div class="container-fluid" style="margin-bottom: 8rem">
            <div class="row" style="margin: 0.7rem">
                <div class="col-sm-6" style="margin-bottom: 3rem">
                    <div style="text-align: center;">
                        <img src="{% static "vid/24002400.jpg" %}"
                                style="width: 90%; box-shadow: 0 0 0.4rem dimgrey;" alt="">
                    </div>
                </div>
                <div class="col-sm-6" style="text-align: left; ">
                    <div style="margin: 0 0 0 .7rem;">
                        <pre style="white-space: pre-wrap; font-size: .94rem;"><I><B>“어디서 왔고 어디로 가는가”</B> 는
현실 안에서 이상을 꿈꾸는 두 청년이 만나
그들이 원하던 이상적인 사운드를 표현하고자 팀을 결성했다.

새로운 음악적 시도를 목표로 제작한 “우주에 두고 왔어요”는
인간이 평소에 헤매이고 고뇌하는 모습을
우주 속 돌아다니는 우리의 모습으로 미화하여
듣는 모두에게 위로를 전하는 노래이다.

끊임없는 고찰을 통해 자신을 알아간다.
도착지를 정해두지 않고 일어나는 미래지향적인 나아감은
팀의 무한한 가능성을 의미한다.

우린 어디서 왔고 어디론가 가고있다
그래서 우리가 있다.




- Credits -
<h5 style="margin-top: 0.5rem; font-size: calc(0.9rem + 0.5vw) !important"><B>어디서 왔고 어디로 가는가 &lt;우주에 두고 왔어요&gt;</B></h5>
어디서 왔고 어디로 가는가 members / 비츠로, 전우뇌

작사 / 작곡  전우뇌 비츠로
편곡 비츠로 전우뇌
믹스 전우뇌, Mushroomshake
마스터링 Mushroomshake
아트 용유


<h5 style="font-size: calc(0.9rem + 0.5vw) !important"><B>wherecomewherego &lt;I left you in the space&gt;</B></h5>
wherecomewherego members/ bitzro, jeonwoonoe

Composed  & Written by bitzro, jeonwoonoe
Produced by bitzro, jeonwoonoe
Mixed by jeonwoonoe, Mushroomshake
Mastering by Mushroomshake
Artwork by yong_yu
                        </I></pre>

                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

accountapp/templates/accountapp/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="bg my-4">
        <video muted autoplay loop playsinline>
{#            <source src="{% static 'vid/배경.mp4' %}" type="video/mp4">#}
            <source src="{% static 'vid/Logo/wcomewgo.mp4' %}" type="video/mp4">
         </video>
{#          <div class="text" style="vertical-align: center">#}
{#            <img src="{% static 'vid/Logo/wcomewgo 그래픽만.png' %}" alt=""#}
{#                        style="position: absolute; width: 100%; top: 50%; left: 50%;#}
{#                        transform: translate(-50%,-50%); vertical-align: center;>">#}
{#          </div>#}
{#          <div>#}
{#            <h1 style="font-size: calc(.6rem + 2vw); color: white; text-align: center;!important;">#}
{#                <I>Where Come Where Go ?</I></h1>#}
{#            <p style="margin: 4vw; font-size: calc(.1rem + 1vw) !important;">#}
{#                We left it in space.</p>#}
{#          </div>#}
    </div>

    <hr style="margin: 0 0 5rem 0">

    <div style="margin: 0 2rem 10rem 2rem">

        <h4 class="IHAGI_logo" style="font-size: 1.9rem"><B> 어디서왔고어디로가는가 </B></h4>
        <p style="margin: 0 0 4rem .8rem; vertical-align: center">
            <a href="https://www.instagram.com/wherecomewherego/" target='_blank'>
                <span><i class="bi bi-instagram"></i></span>
                <I> wherecomewherego </I>
            </a>
        </p>

        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-4" style="margin-bottom: 2.5rem">
                    <h4 class="IHAGI_logo" style="margin-bottom: 3.5rem"><B> - Members </B></h4>
                    <div style="margin-left: 1rem">
                        <h4 class="my-3 IHAGI_logo" style="font-size: 1.1rem"> 비츠로 (bitzro) </h4>
                         <p style="margin: 0 0 2rem .5rem; vertical-align: center; font-size: .7rem">
                             <a href="https://www.instagram.com/juyubi/" target='_blank'>
                                <span><i class="bi bi-instagram"></i></span>
                                <I> juyubi </I>
                             </a>
                        </p>
                        <h4 class="my-3 IHAGI_logo" style="font-size: 1.1rem"> 전우뇌 (jeonwoonoe) </h4>
                        <p style="margin: 0 0 2rem .5rem; vertical-align: center; font-size: .7rem">
                            <a href="https://www.instagram.com/jeonwoonoe/" target='_blank'>
                                <span><i class="bi bi-instagram"></i></span>
                                <I> jeonwoonoe </I>
                            </a>
                        </p>
                    </div>
                </div>
                <div class="col-sm-4" style="margin-bottom: 2.5rem">
                    <h4 class="IHAGI_logo" style="margin-bottom: 3.5rem"><B> - Logo Design </B></h4>
                    <div style="margin-left: 1rem">
                        <h4 class="my-3 IHAGI_logo" style="font-size: 1.1rem"> 김민하 (keemmeenha) </h4>
                         <p style="margin: 0 0 2rem .5rem; vertical-align: center; font-size: .7rem">
                             <a href="https://www.instagram.com/keemmeenha.mmn/" target='_blank'>
                                <span><i class="bi bi-instagram"></i></span>
                                <I> keemmeenha.mmm</I>
                             </a>
                        </p>
                    </div>
                </div>
                <div class="col-sm-4">
                    <h4 class="IHAGI_logo" style="margin-bottom: 3.5rem"><B> - Web Develop </B></h4>
                    <div style="margin-left: 1rem">
                        <h4 class="my-3 IHAGI_logo" style="font-size: 1.1rem"> 신하섬 (IHAGI) </h4>
                         <p style="margin: 0 0 0 .5rem; vertical-align: center; font-size: .7rem">
                             <a href="https://www.instagram.com/nnakeseomnoiz/" target='_blank'>
                                <span><i class="bi bi-instagram"></i></span>
                                <I> nnakeseomnoiz </I>
                             </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <style>
        .container{
            padding: 0;
            margin: auto;
        }

        .container div {
          width: 45%;
            max-width: 250px;
          display: flex;
          justify-content: center;
          align-items: center;
            
        }

        .container img {
            width: 100%;
        }

    </style>

    <div class="container">
      <div class="item1">
          <img src="{% static "vid/사이트 샤진/1.jpg" %}" alt="">
      </div>
      <div class="item2">
          <img src="{% static "vid/사이트 샤진/2.jpg" %}" alt="">
      </div>
      <div class="item3">
          <img src="{% static "vid/사이트 샤진/7.jpeg" %}" alt="">
      </div>
      <div class="item4">
          <img src="{% static "vid/사이트 샤진/4.jpg" %}" alt="">
      </div>
      <div class="item5">
          <img src="{% static "vid/사이트 샤진/5.jpeg" %}" alt="">
      </div>
      <div class="item6">
          <img src="{% static "vid/사이트 샤진/6.jpeg" %}" alt="">
      </div>
      <div class="item7">
          <img src="{% static "vid/사이트 샤진/8.jpeg" %}" alt="">
      </div>
      <div class="item8">
          <img src="{% static "vid/사이트 샤진/11.jpeg" %}" alt="">
      </div>
      <div class="item9">
          <img src="{% static "vid/사이트 샤진/9.jpeg" %}" alt="">
      </div>
      <div class="item10">
          <img src="{% static "vid/사이트 샤진/10.jpeg" %}" alt="">
      </div>
      <div class="item11">
          <img src="{% static "vid/사이트 샤진/3.jpg" %}" alt="">
      </div>
      <div class="item12">
          <img src="{% static "vid/사이트 샤진/12.jpeg" %}" alt="">
      </div>
      <div class="item13">
          <img src="{% static "vid/사이트 샤진/13.jpeg" %}" alt="">
      </div>
      <div class="item14">
          <img src="{% static "vid/사이트 샤진/14.jpeg" %}" alt="">
      </div>
      <div class="item15">
          <img src="{% static "vid/사이트 샤진/15.jpeg" %}" alt="">
      </div>
      <div class="item16">
          <img src="{% static "vid/사이트 샤진/16.jpeg" %}" alt="">
      </div>
      <div class="item17">
          <img src="{% static "vid/사이트 샤진/17.jpeg" %}" alt="">
      </div>
      <div class="item18">
          <img src="{% static "vid/사이트 샤진/18.jpeg" %}" alt="">
      </div>
      <div class="item19">
          <img src="{% static "vid/사이트 샤진/19.jpeg" %}" alt="">
      </div>
      <div class="item20">
          <img src="{% static "vid/사이트 샤진/20.jpeg" %}" alt="">
      </div>
      <div class="item21">
          <img src="{% static "vid/사이트 샤진/21.jpeg" %}" alt="">
      </div>
      <div class="item22">
          <img src="{% static "vid/사이트 샤진/22.jpeg" %}" alt="">
      </div>




    </div>


    <script src="{% static 'js/magicgrid.js' %}"></script>



{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family: 'AppleSDGothicNeoR'">

    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div class="where_footer">

    <div class="beauty_footer">
        <span style="font-family: 'Noto Serif KR', serif;">아름다움 다음 너머</span>
    </div>
    <div style="margin-top: 1rem;">
        <h6 class="IHAGI_logo">IHAGI</h6>
    </div>

</div>

templates/head.html
{% load static %}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>어디서 왔고 어디로 가는가</title>

    {#  BOOTSTRAP LINK  #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    {#  GOOGLE FONT LINK  #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@200&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lora&display=swap" rel="stylesheet">

    {#  DEFAULT CSS LINK  #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    {# BOOTSTRAP CND #}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <style>
        @font-face {
            font-family: 'AppleSDGothicNeoR';
            src: local('AppleSDGothicNeoR'),
            url("{% static 'fonts/AppleSDGothicNeoR.ttf' %}") format("truetype");
        }
        @font-face {
            font-family: 'NanumSquareOTFBold';
            src: local('NanumSquareOTFBold'),
            url("{% static 'fonts/NanumSquareOTFBold.otf' %}") format("opentype");
        }
    </style>


</head>

templates/header.html
    <div class="where_header">

        <div class="IHAGI_logo" style="margin-top: 3rem;">
            <a href="{% url 'home' %}" onmouseover="this.style.color='black'">
                <h1>wherecomewherego</h1>
            </a>
        </div>
        <div class="where_header_button">
            <a href="{% url 'accountapp:album' %}">
                <span class="IHAGI_logo mx-2">Albums</span>
            </a>
            <a href="{% url 'articleapp:list' %}">
                <span class="IHAGI_logo mx-2">Photos</span>
            </a>
        </div>
    </div>